services:
  react-app:
    image: react-app
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  node-web-api:
    image: node-web-api
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - mern-app

  nginx:
    image: nginx:1.21.5-alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - node-web-api
      - react-app
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge